language: cpp

dist: focal

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          packages:
            - cmake
            - g++-8
      env: COMPILER=g++-8 CXXSTD=17
    - compiler: gcc
      addons:
        apt:
          packages:
            - cmake
            - g++-9
      env: COMPILER=g++-9 CXXSTD=17
    - compiler: gcc
      addons:
        apt:
          packages:
            - cmake
            - g++-10
      env: COMPILER=g++-10 CXXSTD=17
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-focal-5.0
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - clang++-5.0
            - libc++-dev
      env: COMPILER=clang++-5.0 CXXSTD=17
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-focal-6.0
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - clang++-6.0
      env: COMPILER=clang++-6.0 CXXSTD=17
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-focal-7.0
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - clang++-7.0
      env: COMPILER=clang++-7.0 CXXSTD=17
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-focal-8.0
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - clang++-8.0
      env: COMPILER=clang++-8.0 CXXSTD=17
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-focal-9.0
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - clang++-9.0
      env: COMPILER=clang++-9.0 CXXSTD=17
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-focal-10.0
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - clang++-10.0
      env: COMPILER=clang++-10.0 CXXSTD=17
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-focal-11.0
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - clang++-11.0
      env: COMPILER=clang++-11.0 CXXSTD=17


install:
  - if [ "$CXX" = "clang++" ]; then export CXX="$COMPILER -stdlib=libc++"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="$COMPILER"; fi

script:
  - /usr/bin/cmake -B build -S . "-DCMAKE_CXX_STANDARD=$CXXSTD"
  - /usr/bin/cmake --build build
  - /usr/bin/cmake --build build --target atl_expected_tests
  - build/atl_expected_tests