language: cpp

dist: focal

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          packages:
            - g++-7
      env: COMPILER=g++-7 CXXSTD=17
    - compiler: gcc
      addons:
        apt:
          packages:
            - g++-8
      env: COMPILER=g++-8 CXXSTD=17
    - compiler: gcc
      addons:
        apt:
          packages:
            - g++-9
      env: COMPILER=g++-9 CXXSTD=17
    - compiler: gcc
      addons:
        apt:
          packages:
            - g++-10
      env: COMPILER=g++-10 CXXSTD=17
    - compiler: clang
      addons:
        apt:
          packages:
            - clang++-10.0
            - libc++-dev
      env: COMPILER=clang++-9.0 CXXSTD=17


before_install:
  - sudo apt update

install:
  - if [ "$CXX" = "clang++" ]; then export CXX="$COMPILER -stdlib=libc++"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="$COMPILER"; fi
  - sudo apt install -y cmake

script:
  - /usr/bin/cmake -B build -S . "-DCMAKE_CXX_STANDARD=$CXXSTD"
  - /usr/bin/cmake --build build
  - /usr/bin/cmake --build build --target atl_expected_tests
  - build/atl_expected_tests